pluginManagement { // <--- Add this block
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal() // Good to have for other Gradle plugins
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "AndroidMotionVideo"
include ':modules:motionlib'
include ':modules:templates'
include ':modules:core'
include ':modules:jcodec-motion-ext'
include ':modules:media3-motion-ext'
include ':modules:ffmpeg-motion-ext'
include ':modules:ffmpeg-kit'
include ':modules:3d-filament-renderer'
include ':modules:3d-opengl-renderer'
include ':modules:tensorflow-motion-ext'
include ':modules:pytorch-motion-ext'
include ':modules:sdui'
include ':modules:metadata-extractor'
include ':modules:motion-store'
include ':modules:motion-video-player'
include ':modules:motion-video-editor'
include ':modules:ml-kit-ext'

if (!System.env.JITPACK) {
    include ':modules:app'
    include ':modules:ivi-demo'
    include ':modules:lyrics-maker'  
}