plugins {
    alias(libs.plugins.android.application)
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "com.tejpratapsingh.animator"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
    namespace 'com.tejpratapsingh.animator'
}

dependencies {
    implementation project(path: ':modules:core')
    implementation libs.androidx.appcompat
    implementation libs.google.android.material
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.work.runtime.ktx

    implementation project(path: ':modules:3d-filament-renderer')
    implementation project(path: ':modules:3d-opengl-renderer')
    implementation project(path: ':modules:motionlib')
    implementation project(path: ':modules:jcodec-motion-ext')
    implementation project(path: ':modules:ffmpeg-motion-ext')
    implementation project(path: ':modules:tensorflow-motion-ext')
//    implementation project(path: ':modules:pytorch-motion-ext')

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
}
