[versions]
constraintlayoutVersion = "2.2.1"
contourVersion = "1.1.0"
filamentAndroidVersion = "1.57.1"
jcodecVersion = "0.2.5"
ktorClientCoreVersion = "3.2.3"
ktx_version = "1.16.0"
appcompat_version = "1.7.1"
material_version = "1.12.0"
lifecycle_runtime_ktx = "2.9.2"
removebgVersion = "1.0.4"
smartExceptionJavaVersion = "0.2.1"
tensorflowLiteTaskVisionVersion = "0.4.4"
tensorflowLiteVersion = "2.17.0"
work_version = "2.10.3"
junit_version = "4.13.2"
androidx_test_ext_junit_version = "1.3.0"
espresso_core_version = "3.7.0"
agpVersion = "8.12.0"
kotlinVersion = "2.2.0"

[libraries]
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx_version" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat_version" }
contour = { module = "app.cash.contour:contour", version.ref = "contourVersion" }
filament-android = { module = "com.google.android.filament:filament-android", version.ref = "filamentAndroidVersion" }
filament-utils-android = { module = "com.google.android.filament:filament-utils-android", version.ref = "filamentAndroidVersion" }
gltfio-android = { module = "com.google.android.filament:gltfio-android", version.ref = "filamentAndroidVersion" }
google-android-material = { group = "com.google.android.material", name = "material", version.ref = "material_version" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle_runtime_ktx" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work_version" }

jcodec = { module = "org.jcodec:jcodec", version.ref = "jcodecVersion" }
jcodec-android = { module = "org.jcodec:jcodec-android", version.ref = "jcodecVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit_version" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx_test_ext_junit_version" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_core_version" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCoreVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCoreVersion" }
removebg = { module = "com.github.erenalpaslan:removebg", version.ref = "removebgVersion" }
smart-exception-java = { module = "com.arthenica:smart-exception-java", version.ref = "smartExceptionJavaVersion" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLiteVersion" }
tensorflow-lite-gpu-delegate-plugin = { module = "org.tensorflow:tensorflow-lite-gpu-delegate-plugin", version.ref = "tensorflowLiteTaskVisionVersion" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteTaskVisionVersion" }
tensorflow-lite-task-vision = { module = "org.tensorflow:tensorflow-lite-task-vision", version.ref = "tensorflowLiteTaskVisionVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agpVersion" }
android-library = { id = "com.android.library", version.ref = "agpVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }

[bundles]
androidx = [
    "androidx-constraintlayout",
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-lifecycle-runtime-ktx",
    "androidx-work-runtime-ktx"
]
filament = [
    "filament-android",
    "filament-utils-android",
    "gltfio-android"
]
jcodec = [
    "jcodec",
    "jcodec-android"
]
ktor = [
    "ktor-client-cio",
    "ktor-client-core"
]
test = [
    "junit",
    "androidx-test-ext-junit",
    "androidx-test-espresso-core"
]
material = [
    "google-android-material"
]
contour = [
    "contour"
]
smart-exception = [
    "smart-exception-java"
]
tensorflow-lite = [
    "tensorflow-lite-gpu-delegate-plugin",
    "tensorflow-lite-task-vision",
    "tensorflow-lite-support",
    "tensorflow-lite"
]