plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.tejpratapsingh.ivi_demo'
    compileSdk 36

    defaultConfig {
        applicationId "com.tejpratapsingh.ivi_demo"
        minSdk 25
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation project(path: ':modules:core')
    implementation libs.androidx.appcompat
    implementation libs.google.android.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout

    implementation project(path: ':modules:motionlib')

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.androidx.test.espresso.core
}