plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace 'com.tejpratapsingh.motionlib.ui.custom.video'
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk libs.versions.minSdk.get().toInteger()

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        compose true
    }
}

dependencies {
    api project(path: ':modules:motionlib')
    api project(path: ':modules:core')
    
    implementation libs.androidx.appcompat
    
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose
    implementation(libs.compose.material.icons.extended)

    testImplementation libs.junit
}
