package com.tejpratapsingh.lyricsmaker.presentation.compose.details

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.PlayCircle
import androidx.compose.material.icons.rounded.Refresh
import androidx.compose.material.icons.rounded.Share
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.adaptive.currentWindowAdaptiveInfoV2
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.work.WorkInfo
import androidx.work.WorkManager
import com.tejpratapsingh.lyricsmaker.presentation.compose.details.compact.ProjectDetailsCompact
import com.tejpratapsingh.lyricsmaker.presentation.compose.details.expanded.ProjectDetailsExpanded
import com.tejpratapsingh.lyricsmaker.presentation.motion.getLyricsVideoProducer
import com.tejpratapsingh.lyricsmaker.presentation.worker.LyricsMotionWorker
import com.tejpratapsingh.motionlib.core.motion.MotionVideoProducer
import com.tejpratapsingh.motionlib.ui.custom.video.MotionVideoPlayerCompose
import com.tejpratapsingh.motionstore.extensions.createProjectFile
import com.tejpratapsingh.motionstore.tables.MotionProject
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@Composable
@Suppress("ktlint:standard:function-naming")
fun ProjectDetailsScreen(
    project: MotionProject,
    onBackClick: () -> Unit,
    onEditClick: (MotionProject) -> Unit,
    onShareClick: (MotionProject) -> Unit,
    onNavigateToAssetDownload: (String) -> Unit,
    onCheckPendingDownloads: (String) -> Boolean,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    val motionVideoProducer by produceState<MotionVideoProducer?>(initialValue = null, project) {
        value =
            withContext(Dispatchers.IO) {
                getLyricsVideoProducer(context, project)
            }
    }

    val workInfos by WorkManager
        .getInstance(context)
        .getWorkInfosByTagFlow(LyricsMotionWorker.getWorkTag(project.id))
        .collectAsState(initial = emptyList())

    val isRendering =
        remember(workInfos) {
            workInfos.any { it.state == WorkInfo.State.RUNNING || it.state == WorkInfo.State.ENQUEUED }
        }

    var showReRenderConfirmation by remember { mutableStateOf(false) }

    if (showReRenderConfirmation) {
        ReRenderConfirmationDialog(
            onConfirm = {
                showReRenderConfirmation = false
                LyricsMotionWorker.startWork(context, project.id)
            },
            onDismiss = { showReRenderConfirmation = false },
        )
    }

    val isVideoGenerated by produceState(initialValue = false, project.id, isRendering) {
        value =
            withContext(Dispatchers.IO) {
                context.createProjectFile(project).exists()
            }
    }

    val adaptiveInfo = currentWindowAdaptiveInfoV2()
    val isWideScreen =
        adaptiveInfo.windowSizeClass.windowWidthSizeClass == androidx.window.core.layout.WindowWidthSizeClass.EXPANDED

    if (isWideScreen) {
        ProjectDetailsExpanded(
            project = project,
            motionVideoProducer = motionVideoProducer,
            isRendering = isRendering,
            isVideoGenerated = isVideoGenerated,
            onBackClick = onBackClick,
            onEditClick = onEditClick,
            onShareClick = {
                val hasPending = onCheckPendingDownloads(project.sdui.toString())
                if (hasPending) {
                    onNavigateToAssetDownload(project.id)
                } else {
                    onShareClick(project)
                }
            },
            onGenerateVideoClick = {
                val hasPending = onCheckPendingDownloads(project.sdui.toString())
                if (hasPending) {
                    onNavigateToAssetDownload(project.id)
                } else {
                    LyricsMotionWorker.startWork(context, project.id)
                }
            },
            onReRenderClick = { showReRenderConfirmation = true },
            onCheckPendingDownloads = onCheckPendingDownloads,
            onNavigateToAssetDownload = onNavigateToAssetDownload,
            modifier = modifier
        )
    } else {
        ProjectDetailsCompact(
            project = project,
            motionVideoProducer = motionVideoProducer,
            isRendering = isRendering,
            isVideoGenerated = isVideoGenerated,
            onBackClick = onBackClick,
            onEditClick = onEditClick,
            onShareClick = {
                val hasPending = onCheckPendingDownloads(project.sdui.toString())
                if (hasPending) {
                    onNavigateToAssetDownload(project.id)
                } else {
                    onShareClick(project)
                }
            },
            onGenerateVideoClick = {
                val hasPending = onCheckPendingDownloads(project.sdui.toString())
                if (hasPending) {
                    onNavigateToAssetDownload(project.id)
                } else {
                    LyricsMotionWorker.startWork(context, project.id)
                }
            },
            onReRenderClick = { showReRenderConfirmation = true },
            onCheckPendingDownloads = onCheckPendingDownloads,
            onNavigateToAssetDownload = onNavigateToAssetDownload,
            modifier = modifier
        )
    }
}

@Composable
private fun ReRenderConfirmationDialog(
    onConfirm: () -> Unit,
    onDismiss: () -> Unit,
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        confirmButton = {
            TextButton(
                onClick = onConfirm,
            ) {
                Text("Re-render")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        },
        title = {
            Text(text = "Re-render Video?")
        },
        text = {
            Text(text = "Are you sure you want to re-render this video? This will overwrite the existing video file.")
        },
    )
}

@Composable
internal fun VideoPlayerSection(
    motionVideoProducer: MotionVideoProducer?,
    onCheckPendingDownloads: () -> Boolean,
    onNavigateToAssetDownload: () -> Unit,
    modifier: Modifier = Modifier,
) {
    Box(
        modifier =
        modifier
            .fillMaxWidth()
            .background(Color.Black),
    ) {
        motionVideoProducer?.let {
            MotionVideoPlayerCompose(
                motionVideoProducer = it,
                onBeforePlay = {
                    val hasPending = onCheckPendingDownloads()
                    if (hasPending) {
                        onNavigateToAssetDownload()
                        false
                    } else {
                        true
                    }
                },
                modifier = Modifier.fillMaxSize(),
            )
        }
    }
}

@Composable
internal fun ProjectInfoSection(
    project: MotionProject,
    isRendering: Boolean,
    isVideoGenerated: Boolean,
    onShareClick: () -> Unit,
    onGenerateVideoClick: () -> Unit,
    onReRenderClick: () -> Unit,
    modifier: Modifier = Modifier,
) {
    Surface(
        tonalElevation = 2.dp,
        shadowElevation = 8.dp,
        modifier = modifier.fillMaxWidth(),
    ) {
        Column(
            modifier =
            Modifier
                .fillMaxWidth()
                .padding(24.dp),
        ) {
            Text(
                text = project.name,
                style = MaterialTheme.typography.headlineSmall,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.onSurface,
            )

            val startTime = project.metadata.get("startTime")?.asInt ?: 0
            Text(
                text = "Starts at: ${startTime}s",
                style = MaterialTheme.typography.bodyLarge,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )

            Spacer(modifier = Modifier.height(24.dp))

            ActionButtons(
                isRendering = isRendering,
                isVideoGenerated = isVideoGenerated,
                onShareClick = onShareClick,
                onGenerateVideoClick = onGenerateVideoClick,
                onReRenderClick = onReRenderClick,
            )
        }
    }
}

@Composable
private fun ActionButtons(
    isRendering: Boolean,
    isVideoGenerated: Boolean,
    onShareClick: () -> Unit,
    onGenerateVideoClick: () -> Unit,
    onReRenderClick: () -> Unit,
) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Button(
            onClick = {
                if (isVideoGenerated) {
                    onShareClick()
                } else {
                    onGenerateVideoClick()
                }
            },
            enabled = !isRendering,
            modifier =
            Modifier
                .weight(1f)
                .height(56.dp),
            shape = RoundedCornerShape(16.dp),
        ) {
            Icon(
                imageVector =
                if (isRendering) {
                    Icons.Rounded.PlayCircle
                } else if (isVideoGenerated) {
                    Icons.Rounded.Share
                } else {
                    Icons.Rounded.PlayCircle
                },
                contentDescription = null,
                modifier = Modifier.size(20.dp),
            )
            Spacer(modifier = Modifier.width(12.dp))
            Text(
                text =
                if (isRendering) {
                    "Rendering..."
                } else if (isVideoGenerated) {
                    "Share Project"
                } else {
                    "Generate Video"
                },
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.SemiBold,
            )
        }

        if (isVideoGenerated) {
            Spacer(modifier = Modifier.width(12.dp))
            IconButton(
                onClick = onReRenderClick,
                enabled = !isRendering,
                modifier =
                Modifier
                    .size(56.dp)
                    .background(
                        color =
                        if (isRendering) {
                            MaterialTheme.colorScheme.surfaceVariant
                        } else {
                            MaterialTheme.colorScheme.secondaryContainer
                        },
                        shape = RoundedCornerShape(16.dp),
                    ),
            ) {
                Icon(
                    imageVector = Icons.Rounded.Refresh,
                    contentDescription = "Re-render",
                    tint =
                    if (isRendering) {
                        MaterialTheme.colorScheme.onSurfaceVariant
                    } else {
                        MaterialTheme.colorScheme.onSecondaryContainer
                    },
                )
            }
        }
    }
}
